---
name: Create GitHub Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  call_build_dists:
    uses: ./.github/workflows/build_dists.yml

  create_gh_release:
    needs: [call_build_dists]
    runs-on: ubuntu-latest
    # don't do this action on forks by default
    if: github.event_name == 'push' && github.repository == 'hpyproject/hpy'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          # consider tags in form '*.*.*rc*' to indicate a pre-release
          prerelease: ${{ contains(github.ref, 'rc') }}
